syntax = "proto3";

package user;

option go_package = "gRPC-example/proto;proto";

import "google/protobuf/empty.proto";

service UserCreateService {
    rpc SaveUser (SaveUserRequest) returns (SaveUserResponse);
}

service UserGetAllService {
    rpc GetUsers (google.protobuf.Empty) returns (ListUserResponse);    
}

service UpdateUser {
    rpc UpdateUser (UpdateUserRequest) returns (UpdateUserResponse);
}

message User {
    int32 ID = 1; 
    string username = 2; 
    string password = 3; 
}

message SaveUserRequest {
    string username = 2;
    string password = 3;
}

message SaveUserResponse {
    bool response = 1;
    string message = 2;
}

message ListUserResponse {
    repeated User users = 1; 
}

message UpdateUserRequest {
    int32 ID = 1;
    string username = 2; 
    string password = 3; 
}

message UpdateUserResponse {
    bool success = 1; 
    string message = 2;  
}
